[default.probe]
protocol = "Jtag"

[default.general]
chip = "esp32c3"

[default.rtt]
enabled = true
# up_mode = "NoBlockTrim"
up_mode = "BlockIfFull"
channels = [
	{ up = 0, down = 0, name = "Firmware logs via defmt", format = "Defmt" },
]

[monitor.flashing]
enabled = false
